---
title: "Project 1"
author: "Data 350"
date: "Due date"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Overview

In this project, you will produce an exploratory data analysis (EDA) report for the 

- Option 1: `NHANES::NHANESraw` dataset. **Warning::** You are not allowed to use the `NHANES::NHANES` dataset. 
- Option 2: `forcats::gss_cat`


## Instruction


1. Define a question/task (or a few related questions) that will guide your exploration. 

2. Create 6-10 figures from the data exploring your question(s)
  - at least one figure must be a geospatial map (the maps package will be helpful for this)
  - at least one figure must be faceted
  - each figure must be multivariate and show at least two of the plotting techniques we learned in class
  - all figures must be well-labeled
  - no more than two figures of the same type (counted using `geom_`, if you include >8 figures, you are allowed to have more than 2 of a given type)

3. Submission: one `RMD` and one `HTML` files. The `HTML` file should only consist of words and plots, i.e., no code. To do this, you can set `echo = F` in the global options. 




