---
title: "Measle"
author: "Fushuai Jiang"
date: "2025-05-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(ggplot2)
library(tidyverse)
library(sf)
library(readr)
library(leaflet)
```



Loading data
```{r}
measles_state <- read.csv('measle_by_state.csv') # need cleaning
measles_year <- read.csv('measle_by_year.csv')
measles_week <- read.csv('measles_by_week.csv')
vaccine_state <- read.csv('vaccine_by_state.csv')
```

Cleaning measles by year
```{r}
measles_year$filter <- NULL
```

Cleaning measles by week
```{r}
measles_week <- measles_week |> mutate(week = week_start) |> select(week, everything())
measles_week$week <- as.Date(measles_week$week)
```

Time series plot for measle cases

```{r}
data <- measles_week 
g <- ggplot(data, aes(x = week, y = cases)) + 
  geom_line() + 
  labs(
    x = "Date",
    y = "Cases",
    title = "Measles Cases Since 2023",
    caption = "Source: CDC"
  ) + 
  geom_vline(xintercept = as.Date("2025-01-20"), color = 'red', linewidth = 1.2) + 
  theme_bw()
g
```
Cleaning vaccination by states

```{r}
library(maps)
library(viridis)

us_states <- map_data('state')

vaccine_state <- vaccine_state |> mutate(region = tolower(geography))
vaccine_state$estimate_pct <- as.numeric(gsub("%","", vaccine_state$estimate_pct))

vacc_map <- left_join(us_states, vaccine_state, by = "region", relationship = "many-to-many")


```

Visualize it

```{r}
ggplot(vacc_map, aes(x = long, y = lat, group = group, fill = estimate_pct)) +
  geom_polygon(color = "white") +
  coord_fixed(1.3) +
  scale_fill_viridis(name = "Vaccination Rate (%)", option = "C") +
  labs(title = "Vaccination Rates by State") + 
  theme_minimal()
```

