---
title: "Project 1"
author: "Data 350"
date: "Due date: October 17 2025 at midnight (EST)"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Overview

In this project, you will produce an exploratory data analysis (EDA) report for the `NHANES::NHANESraw` dataset. **Warning:** You are not allowed to use the `NHANES::NHANES` dataset. 



## Instruction


1. Define a set of questions/tasks that will guide your exploration. 

2. Create 6-10 figures from the data exploring your questions.
  
    - at least one figure must be faceted using `facet_`
    - each counted figure must be multivariate and show at least two of the plotting techniques we learned in class
    - You must utilize at least 2 plotting techniques from the **Additional Topics** module
    - all figures must be well-labeled
    - no more than two figures of the same type (counted using `geom_`, if you include $>8$ figures, you are allowed to have more than 2 of a given type)

3. Write a report with your figures included. 

## Submission

- A `zip` file consisting of one `RMD` and one `HTML` files. The name of your `zip` file should be a two-digit number corresponding to your group. 
- The knitted output of the `RMD` file must be identical to the `HTML` file.
- The `HTML` file should only consist of words and plots, i.e., no code. To do this, you can set `echo = F` in the global options.  


## Grading structure

The precise rubric will be published via ELMS. You will be graded on:

  1. Basic completion according to the instruction
  2. Depths of your guiding questions
  3. Suitable plot types
  4. Meaningful statistical analysis/transforms to support your questions and provide additional insights
  5. Statistical rigor, including but not restricted to: expressing uncertainty, explanation why/how the methods work, reproducibility of the experiments
  
## Group Structure 

The following applies to a standard 3-person group. I will make suitable adjustment for the non-standard group. 



| Role | Responsibilities |
|------|----------------|
| **Project Leader/Manager** | - Guides the overall direction of the EDA project <br> - Organizes workflow, deadlines, communication (with team members and the instructor), and file submission  |
|||
| **Data/Stat Lead** | - Performs data cleaning, transformations, and statistical analysis<br>- Provides technical support to others |
|||
| **Visualization/Communication Lead** | - Designs clear, well-labeled, and statistically informed figures<br>- Standardizes figures/texts and integrate them into report<br>|
|||
| **All Members** | - Each member is responsible for at $\geq 2$ plots, and must draft texts for their own plots <br> - Each member is responsible for writing a post-production report |

> **Note:** Roles have some degree of flexiblility; members can overlap responsibilities. Every member must contribute technically, write text, and support quality control.


## Post-production

Each member is required to submit a report including an individual reflection and a group member evaluation. Both will be available only to the instructor/grader. Each report must include the following key information:

- Your roles and your plots (1 paragraph)
- Summary of your work (1 paragraph)
- Evaluation of each of your team member's work, i.e., what aspects are done well and what could be improved for each member. (1 paragraph for each member)





