---
title: "Syllabus: Data350 Fall 2025"
subtitle: "Data Visualization and Presentation"
author: "Fushuai Jiang, University of Maryland"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)
```

## Basic information

- Instructor: Dr. Fushuai Jiang
- Office Hours: by appointment (usually via Zoom)
- Textbooks: everything will be freely available online
- Last day of in-person instruction: November 20. (The weeks after Thanksgiving break will be for you to do/review projects)
- Prerequesites: STAT100, MATH135, or any 400-level STAT course; DATA110 or DATA120. I don't expect you to have a coding background. 


## Course Objectives

**Overall:** Introduction to effective and intuitive visual representations of data, including customizing graphics, plotting arrays, statistical graphics, and representing time series. 

**Tentative topics:**

- Principles of data visualization in `R` using `ggplot2`
- Data wrangling using `dplyr`
- Basic plot types such as scatter plots, line plots, bar charts, box plots, and correlation
- geo-spatial plots and heat maps
- interactive dashboard using `Shiny`
- *If time permits:* advanced topics such as model selection, kernel density estimates, and spectrogram

## Grading structure

- This is a heavily project-based course, and for the two projects, you will be working in groups. 
- Your final grade depends on your
  -  Homework (25%)
  -  In-class assessment (15%)
  - Project 1 (25%)
  - Project 2 (25%)
  - Critique (10%)
  
### Homework

- Assigned either weekly or biweekly, depending on how fast we go. Each assignment will be due Monday at midnight. 

- Late Penalty: 10% for each 12 hours (additive). Late time will be round **UP**, i.e., <span style = "color:red">**7 minutes late = 12 hours late**</span>

- Acceptable excuses: document emergencies

- <span style = "color:red">**Non-acceptable excuses:**</span> "my internet wasn't working around midnight

### In-class assessment

- Dates: Last Thursday of each month (for Nov it will be the Thursday before Thanksgiving break)

- In class, paper-based

- Multiple-choice or fill-in-the-blank problems testing basic understanding of graphic syntax in `R`. If you understand your homework and debug the code yourself (i.e. you pass the human verification test), you won't have a problem



### Project 1 & 2

- Rubrics will be given with the projects when they are assigned. You will be working in groups of 3 (outlier: one group of 2 or one group of 4). 



- Both projects will be EDA-stype (Exploratory Data Analysis)

- Project 1: I will give you a dataset, and you will need to produce an EDA report along with an interactive Shiny App

- Project 2: You will need to find your own dataset that interests you (pre-approved needed!), and you will need to produce and EDA report, a set of slides, and **PRESENT IT** over recording. 


### Project critique

- The grade of your project will depend on your peers' evaluation (75%) and my input (25%). Again, clear rubrics will be given, and the median of the grade (per functionality) will be taken.

- Each group will anonymously (to you, not to me) critique 5 other groups, and the feedback will be made available. 

- I will grade your critique, by completion and the level of constructive criticism.

- Malicious language/tone in critiques will be reported to Office of Student Conduct. 



### Groupwork

- I will assign the group (unless you have a strong pitch for members). Each member will have a main role, for instance,
  - Person 1 (leader) design/outline the EDA report and oversee the workflow
  - Person 2 handles data wrangling and basic plotting
  - Person 3 handles fine-tuning and technical writing 
  
  
- Each member within a group receive their individual grade, based on the project critique and **internal evaluation**. Take accountability!

- Part of the group leader's role is to **check in with me weekly** and update me on the project. 

- Trouble within the team? First channel your communication and conflict-resolution skill, especially with the group leader. If that fails, talk to the HR (i.e. me). 



## Ethics:

- You are encouraged to work together outside of the class, especially with your group

- You are allowed to use AI-powered programs to **HELP** you study. 

- **Homework:** you must write your assignment by yourself, with no helps from peers or AIs. Any use of AI-generated work to outline, write, create, or edit your assignments will be considered an academic integrity violation. 
  - My reasoning: they may be biased and may provide false information. Moreover, they don't serve the development of a student. You should not publish code that you do not understand. 
  
- For more information on the Code of Academic Integrity or the Student Honor Council, please visit <http://www.shc.umd.edu>


  
## Accomodation

The University of Maryland is committed to creating and maintaining a welcoming and inclusive educational, working, and living environment for people of all abilities. The University of Maryland is also committed to the principle that no qualified individual with a disability shall, on the basis of disability, be excluded from participation in or be denied the benefits of the services, programs, or activities of the University, or be subjected to discrimination. The University of Maryland provides reasonable accommodations to qualified individuals. Reasonable accommodations shall be made in a timely manner and on an individualized and flexible basis.

Discrimination against individuals on the grounds of disability is prohibited. The University also strictly prohibits retaliation against persons arising in connection with the assertion of rights under this Policy.

Accessibility & Disability Service (ADS) facilitates reasonable accommodations to qualified individuals. For assistance in obtaining accommodation, contact Accessibility and Disability Service at 301.314.7682 or [adsfrontdesk@umd.edu](mailto:adsfrontdesk@umd.edu). More information is available from the Counseling Center.

## Names/Pronouns and Self-Identification

The University of Maryland recognizes the importance of a diverse student body, and we are committed to fostering inclusive and equitable classroom environments. You are invited, if you wish, to tell our instructor how you want to be referred to in class, both in terms of your name and your pronouns (he/him, she/her, they/them, etc.). Keep in mind that the pronouns someone uses are not necessarily indicative of their gender identity. Visit trans.umd.edu to learn more.

Additionally, it is your choice whether to disclose how you identify in terms of your gender, race, class, sexuality, religion, and dis/ability, among all aspects of your identity (e.g., should it come up in classroom conversation about experiences and perspectives) and should be self-identified, not presumed or imposed. Instructors should try to address and refer to all students accordingly, and you should do the same for all of your fellow Terps.

## Communication with Peers

With a diversity of perspectives and experiences, we may find ourselves in disagreement and/or debate with one another. As such, it is important that we agree to conduct ourselves in a professional manner and that we work together to foster and preserve a virtual classroom environment in which we can respectfully discuss and deliberate controversial questions. You are encouraged to confidently exercise your right to free speech—bearing in mind, of course, that you will be expected to craft and defend arguments that support your position. Keep in mind, that free speech has its limit and this course is NOT the space for hate speech, harassment, and derogatory language. Every reasonable attempt should be made to create an atmosphere in which each student feels comfortable voicing their argument without fear of being personally attacked, mocked, demeaned, or devalued. Any behavior (including harassment, sexual harassment, and racially and/or culturally derogatory language) that threatens this atmosphere will not be tolerated. Please alert the instructor or appropriate person immediately if you feel threatened, dismissed, or silenced at any point during the semester and/or if your engagement in discussion has been in some way hindered by the learning environment.

## Notice of Mandatory Reporting

Notice of mandatory reporting of sexual assault, sexual harassment, interpersonal violence, and stalking: A faculty member is designated as a “Responsible University Employee” and must report all disclosures of sexual assault, sexual harassment, interpersonal violence, and stalking to UMD’s Title IX Coordinator per University Policy on Sexual Harassment and Other Sexual Misconduct.

If you wish to speak with someone confidentially, please contact one of UMD’s confidential resources, such as CARE to Stop Violence (located on the Ground Floor of the Health Center) at 301-741-3442 or the Counseling Center (located at the Shoemaker Building) at 301-314-7651.

You may also seek assistance or supportive measures from UMD’s Title IX Coordinator, Angela Nastase, by calling 301-405-1142 or emailing [titleIXcoordinator@umd.edu](mailto:titleIXcoordinator@umd.edu). To view further information on the above, please visit the Office of Civil Rights and Sexual Misconduct's website at <https://ocrsm.umd.edu/>.


